name: Duel
version: 1.0.0
main: com.github.cbplugins.duel.Duel
author: CBPlugins
description: The official duel minigame for minecraft

commands:
  stats:
    usage: /<command> [player]
    description: Shows the stats of the specified player or yourself
  setlobby:
    usage: /<command>
    description: Set the lobby spawn location
  setspawn:
    usage: /<command> [first, second, spectator]
    description: Set the spawn location for the specified type